version: '3'

services:
  # MySQL
  # db:
  #   image: mysql:8.0
  #   container_name: mysql8.0
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_DATABASE: hostnavi
  #     MYSQL_USER: alichan
  #     MYSQL_PASSWORD: alichan
  #     TZ: 'Asia/Tokyo'
  #   command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
  #   volumes:
  #   - ./db/data:/var/lib/mysql
  #   - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
  #   - ./db/sql:/docker-entrypoint-initdb.d
  #   ports:
  #   - 3306:3306
  # テスト用MySQL
  testdb:
    image: mysql:8.0
    container_name: testmysql8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hostnavi
      MYSQL_USER: alichan
      MYSQL_PASSWORD: alichan
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
    - ./testdb/data:/var/lib/mysql
    - ./testdb/my.cnf:/etc/mysql/conf.d/my.cnf
    - ./testdb/sql:/docker-entrypoint-initdb.d
    ports:
    - 3306:3306
  #MinIO
  minio:
    image: minio/minio:RELEASE.2023-02-27T18-10-45Z
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=alichan
      - MINIO_ROOT_PASSWORD=alichan0609
    entrypoint: sh
    command: -c "/opt/bin/minio server /export --address :9000 --console-address :9001"
    volumes:
      - ./minio/data:/export